fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/Adaptavist/puppet-stdlib"
    kmod:
      repo: "https://github.com/Adaptavist/puppet-kmod"
  symlinks:
    'kmod_config': "#{source_dir}"
